load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "scanner",
    srcs = ["Scanner.cpp"],
    hdrs = ["Scanner.h"],
    deps = []
)

